id: 376d92ce-068a-4c74-8332-b9b78d065540
inputs: []
name: Select App-ID URL Results
outputs: []
sourceplaybookid: 0be8c783-78e7-43ec-89ea-2bfa19592e3b
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4cb7a2c8-618b-4408-8060-170cb70e374a
      iscommand: false
      name: ""
      version: -1
    taskid: 4cb7a2c8-618b-4408-8060-170cb70e374a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      "No":
      - "13"
      "Yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d397c850-8a9f-431e-8814-a4ea19686c57
      iscommand: false
      name: Push AppID for ${incident.website}
      type: condition
      version: -1
    taskid: d397c850-8a9f-431e-8814-a4ea19686c57
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 420
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: a0075f26-5dfa-4cde-8fcc-677235b0707d
      iscommand: false
      name: Clear Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: a0075f26-5dfa-4cde-8fcc-677235b0707d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: set
      category: {}
      cmd: {}
      command: {}
      dst: {}
      element:
        simple: ${appidxml}
      from: {}
      job-id: {}
      key: {}
      log-type: {}
      pcap-id: {}
      period: {}
      query: {}
      reportname: {}
      reporttype: {}
      search-time: {}
      serialno: {}
      target: {}
      to: {}
      type:
        simple: config
      using:
        simple: rlemm_labfw
      where: {}
      xpath:
        simple: ${appidxpath}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Run any command supported in the API.
      id: 515c9e44-4c39-4865-8f05-aee3c334bfcf
      iscommand: true
      name: Push Change
      script: Panorama|||panorama
      type: regular
      version: -1
    taskid: 515c9e44-4c39-4865-8f05-aee3c334bfcf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 120,
          "y": 780
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: rlemm_labfw
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Commits a configuration to Palo Alto Firewall or Panorama, but
        does not validate if the commit was successful. Committing to Panorama does
        not push the configuration to the Firewalls. To push the configuration, run
        the panorama-push-to-device-group command.
      id: dfda4d88-7ff9-42f5-8f5e-e325e4e8f12b
      iscommand: true
      name: Commit Changes
      script: Panorama|||panorama-commit
      type: regular
      version: -1
    taskid: dfda4d88-7ff9-42f5-8f5e-e325e4e8f12b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 120,
          "y": 930
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f689c30e-065b-4307-8386-92a57037d7d5
      iscommand: false
      name: BuildWebAppID
      script: 185a55a0-116e-48a6-8592-48455467c175
      type: regular
      version: -1
    taskid: f689c30e-065b-4307-8386-92a57037d7d5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 120,
          "y": 640
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 93b26984-9831-4b88-8d74-ca1b5244517b
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 93b26984-9831-4b88-8d74-ca1b5244517b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 720,
          "y": 1040
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${Panorama.Commit.JobID}
      using:
        simple: rlemm_labfw
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Returns commit status for a configuration.
      id: 2f39bda4-2a17-4420-87db-b35baca7f56f
      iscommand: true
      name: panorama-commit-status
      script: Panorama|||panorama-commit-status
      type: regular
      version: -1
    taskid: 2f39bda4-2a17-4420-87db-b35baca7f56f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 120,
          "y": 1260
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: using
      AdditionalPollingCommandArgValues:
        simple: rlemm_labfw
      Ids:
        complex:
          accessor: JobID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Panorama.Commit.Status
              operator: isEqualString
              right:
                value:
                  simple: Pending
          root: Panorama.Commit
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: job_id
      PollingCommandName:
        simple: panorama-commit-status
      Timeout:
        simple: "60"
      dt:
        simple: Panorama.Commit(val.Status != 'Completed' && val.Status != 'Failed').JobID
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: bc380132-6877-44b6-857e-5f314f013c62
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: bc380132-6877-44b6-857e-5f314f013c62
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 120,
          "y": 1095
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes:
        simple: AppID Created for ${incident.website}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id:
        simple: ${incident.id}
      phishingconfirmationstatus: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 3fb28ae7-7209-4b66-8826-858d6f010343
      iscommand: true
      name: Close Incident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 3fb28ae7-7209-4b66-8826-858d6f010343
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 590,
          "y": 1260
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Panorama.Commit.Status
          operator: isEqualString
          right:
            value:
              simple: Completed
      label: "yes"
    id: "12"
    ignoreworker: false
    nexttasks:
      "yes":
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cc31be31-96cc-4c09-893f-6c48f525e2bf
      iscommand: false
      name: Was Commit Successful
      type: condition
      version: -1
    taskid: cc31be31-96cc-4c09-893f-6c48f525e2bf
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 120,
          "y": 1430
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes:
        simple: Admin declined AppID for ${incident.website}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id:
        simple: ${incident.id}
      phishingconfirmationstatus: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: df25fd18-4710-4951-8fe9-aefcf398251b
      iscommand: true
      name: Close Incident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: df25fd18-4710-4951-8fe9-aefcf398251b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 720,
          "y": 800
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1475,
        "width": 980,
        "x": 120,
        "y": 50
      }
    }
  }
