id: 0be8c783-78e7-43ec-89ea-2bfa19592e3b
inputs: []
name: Select App-ID Payload Results
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4cb7a2c8-618b-4408-8060-170cb70e374a
      iscommand: false
      name: ""
      version: -1
    taskid: 4cb7a2c8-618b-4408-8060-170cb70e374a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: 'Select Ascii Results:'
        options: []
        optionsarg:
        - simple: |-
            Ascii Result 1:
            ${incident.asciiresult1}
        - simple: |-
            Ascii Result 2:
            ${incident.asciiresult2}
        - simple: |-
            Ascii Result 3:
            ${incident.asciiresult3}
        - simple: |-
            Ascii Result 4:
            ${incident.asciiresult4}
        - simple: |-
            Ascii Result 5:
            ${incident.asciiresult5}
        - simple: |-
            Ascii Result 6:
            ${incident.asciiresult6}
        - simple: |-
            Ascii Result 7:
            ${incident.asciiresult7}
        - simple: |-
            Ascii Result 8:
            ${incident.asciiresult8}
        - simple: |-
            Ascii Result 9:
            ${incident.asciiresult9}
        - simple: |-
            Ascii Result 10:
            ${incident.asciiresult10}
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: multiSelect
      sender: ""
      title: 'Select Ascii Results:'
      totalanswers: 0
    id: "1"
    ignoreworker: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3e4f9a5a-53a2-49be-8c8a-d84c2f912bb6
      iscommand: false
      name: Select Ascii Results
      type: collection
      version: -1
    taskid: 3e4f9a5a-53a2-49be-8c8a-d84c2f912bb6
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 150,
          "y": 680
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: a0075f26-5dfa-4cde-8fcc-677235b0707d
      iscommand: false
      name: Clear Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: a0075f26-5dfa-4cde-8fcc-677235b0707d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 170
        }
      }
  "3":
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: 'Select Hex Results:'
        options: []
        optionsarg:
        - simple: |-
            Hex Result 1:
            ${incident.hexresult1}
        - simple: |-
            Hex Result 2:
            ${incident.hexresult2}
        - simple: |-
            Hex Result 3:
            ${incident.hexresult3}
        - simple: |-
            Hex Result 4:
            ${incident.hexresult4}
        - simple: |-
            Hex Result 5:
            ${incident.hexresult5}
        - simple: |-
            Hex Result 6:
            ${incident.hexresult6}
        - simple: |-
            Hex Result 7:
            ${incident.hexresult7}
        - simple: |-
            Hex Result 8:
            ${incident.hexresult8}
        - simple: |-
            Hex Result 9:
            ${incident.hexresult9}
        - simple: |-
            Hex Result 10:
            ${incident.hexresult10}
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: multiSelect
      sender: ""
      title: 'Select Hex Results:'
      totalanswers: 0
    id: "3"
    ignoreworker: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: af5e4315-aea0-480c-8739-61b798b422ad
      iscommand: false
      name: Select Hex Results
      type: collection
      version: -1
    taskid: af5e4315-aea0-480c-8739-61b798b422ad
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 150,
          "y": 855
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6c026129-b678-4b5e-8510-373de8a6e6f2
      iscommand: false
      name: Build Custom AppID
      script: c6273e6d-1f5e-4835-81f6-7688efae4c82
      type: regular
      version: -1
    taskid: 6c026129-b678-4b5e-8510-373de8a6e6f2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 150,
          "y": 1020
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      action:
        simple: set
      category: {}
      cmd: {}
      command: {}
      dst: {}
      element:
        simple: ${appidxml}
      from: {}
      job-id: {}
      key: {}
      log-type: {}
      pcap-id: {}
      period: {}
      query: {}
      reportname: {}
      reporttype: {}
      search-time: {}
      serialno: {}
      target: {}
      to: {}
      type:
        simple: config
      using:
        simple: rlemm_labfw
      where: {}
      xpath:
        simple: ${appidxpath}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Run any command supported in the API.
      id: 515c9e44-4c39-4865-8f05-aee3c334bfcf
      iscommand: true
      name: Push Change
      script: Panorama|||panorama
      type: regular
      version: -1
    taskid: 515c9e44-4c39-4865-8f05-aee3c334bfcf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 150,
          "y": 1170
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: rlemm_labfw
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Commits a configuration to Palo Alto Firewall or Panorama, but
        does not validate if the commit was successful. Committing to Panorama does
        not push the configuration to the Firewalls. To push the configuration, run
        the panorama-push-to-device-group command.
      id: dfda4d88-7ff9-42f5-8f5e-e325e4e8f12b
      iscommand: true
      name: Commit Changes
      script: Panorama|||panorama-commit
      type: regular
      version: -1
    taskid: dfda4d88-7ff9-42f5-8f5e-e325e4e8f12b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 150,
          "y": 1330
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      "No":
      - "13"
      "Yes":
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: eb407407-7547-4781-8a52-ced2a62d6448
      iscommand: false
      name: Build AppID (Yes/No)
      type: condition
      version: -1
    taskid: eb407407-7547-4781-8a52-ced2a62d6448
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 315
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4bbc4ffe-0bd5-4a60-8402-954a3b5a1231
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 4bbc4ffe-0bd5-4a60-8402-954a3b5a1231
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 830,
          "y": 720
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: using
      AdditionalPollingCommandArgValues:
        simple: rlemm_labfw
      Ids:
        complex:
          accessor: JobID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Panorama.Commit.Status
              operator: isEqualString
              right:
                value:
                  simple: Pending
          root: Panorama.Commit
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: job_id
      PollingCommandName:
        simple: panorama-commit-status
      Timeout:
        simple: "60"
      dt:
        simple: Panorama.Commit(val.Status != 'Completed' && val.Status != 'Failed').JobID
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: db811876-3fbd-4d37-8e18-7b8491602490
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: db811876-3fbd-4d37-8e18-7b8491602490
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 150,
          "y": 1490
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      job_id:
        simple: ${Panorama.Commit.JobID}
      using:
        simple: rlemm_labfw
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Returns commit status for a configuration.
      id: 711feb4a-11c0-4773-88dc-b05f7bda7ad0
      iscommand: true
      name: panorama-commit-status
      script: Panorama|||panorama-commit-status
      type: regular
      version: -1
    taskid: 711feb4a-11c0-4773-88dc-b05f7bda7ad0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 150,
          "y": 1640
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Panorama.Commit.Status
          operator: isEqualString
          right:
            value:
              simple: Completed
      label: "yes"
    id: "11"
    ignoreworker: false
    nexttasks:
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3493d8f3-7a39-4fac-8c59-8d136d1163ec
      iscommand: false
      name: Was Commit Successful
      type: condition
      version: -1
    taskid: 3493d8f3-7a39-4fac-8c59-8d136d1163ec
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 150,
          "y": 1880
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes:
        simple: AppID created for ${incident.appidname}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id:
        simple: ${incident.id}
      phishingconfirmationstatus: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: e4ee1105-cc3c-477b-832a-657a1e0d1cfa
      iscommand: true
      name: Close Incident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: e4ee1105-cc3c-477b-832a-657a1e0d1cfa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 820,
          "y": 1750
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes:
        simple: Admin declined AppID for ${incident.appidname}
      closeReason: {}
      code42alerttype: {}
      emailclassification: {}
      id:
        simple: ${incident.id}
      phishingconfirmationstatus: {}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 6e4696de-9929-42a5-8a00-0bf3b8418a28
      iscommand: true
      name: Close Incident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 6e4696de-9929-42a5-8a00-0bf3b8418a28
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 830,
          "y": 520
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.appidname
          operator: match
          right:
            value:
              simple: \S+
      - - left:
            iscontext: true
            value:
              simple: incident.appidsignaturescope
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: incident.appidsignaturename
          operator: match
          right:
            value:
              simple: \S+
      - - left:
            iscontext: true
            value:
              simple: incident.patternmatchcontext
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: incident.appidcategory
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: incident.appidsubcategory
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: incident.appidtechnology
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: incident.appidrisk
          operator: isNotEmpty
      label: "yes"
    id: "14"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "15"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4210c61f-8b05-4757-8505-2989115b56fe
      iscommand: false
      name: Check for Required Fields
      type: condition
      version: -1
    taskid: 4210c61f-8b05-4757-8505-2989115b56fe
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 150,
          "y": 520
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f2c03f22-1b51-4605-860c-c435b08d0587
      iscommand: false
      name: Please complete required fields
      type: title
      version: -1
    taskid: f2c03f22-1b51-4605-860c-c435b08d0587
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -360,
          "y": 460
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1925,
        "width": 1570,
        "x": -360,
        "y": 50
      }
    }
  }
